export default {
    CHANGE_PAGE: 'BOARD/CHANGE_PAGE',
    CLICK_ROW: 'BOARD/CLICK_ROW',
    CLOSE_MODAL: 'BOARD/CLOSE_MODAL',
    MODIFY_DATA: 'BOARD/MODIFY_DATA',
    CLICK_WRITE_BUTTON: 'BOARD/CLICK_WRITE_BUTTON',
    CHANGE_SHOWING_ALL_CONTENTS: 'BOARD/CHANGE_SHOWING_ALL_CONTENTS',
    KEYWORD_SEARCH: 'BOARD/KEYWORD_SEARCH',
    SEARCH_TYPE_SELECTOR_CHANGE: 'BOARD/SEARCH_TYPE_SELECTOR_CHANGE',
    API_REQUEST_ERROR: 'BOARD/API_REQUEST_ERROR'
}
